# ###########################################################################################
# Model: BiLSTM
# Authors: Luca Della Libera 2024
# ###########################################################################################

experiment_name: mimi
dataset: LibriSpeech
task: asr

# Seed needs to be set at top of YAML
seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
train_csv: !ref <save_folder>/train-clean-100.csv
valid_csv: !ref <save_folder>/dev-clean.csv
test_csv: !ref <save_folder>/test-clean.csv
splits: [train-clean-100, dev-clean, test-clean]

# Output folders
output_folder: !ref results/<task>/<dataset>/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save
cache_folder: !name:huggingface_hub.constants.HUGGINGFACE_HUB_CACHE

# Preprocessing parameters
train_remove_if_longer: 60.0  # Seconds
valid_remove_if_longer: 60.0  # Seconds
test_remove_if_longer: 60.0  # Seconds
sorting: ascending
cache_size: 1.e+10

# Training parameters
num_epochs: 60
grad_accumulation_factor: 16
train_batch_size: 1
valid_batch_size: 1
test_batch_size: 1
dataloader_workers: 4
nonfinite_patience: 10
max_grad_norm: 0.01
precision: fp32
ckpt_interval_steps: 10000
keep_checkpoints: 1
augment: False
augment_prob: 0.75

# Special tokens
blank_id: !ref <num_tokens>

# Optimizer parameters
lr: 0.0001
weight_decay: 0.01
improvement_threshold: 0.0025
annealing_factor: 0.9
patient: 1

# Tokenizer parameters
num_tokens: 1000  # If token_type=char, must be equal to the number of found characters
token_type: bpe  # ["unigram", "bpe", "char"]
character_coverage: 1.0

# Codec parameters
sample_rate: 24000
vocab_size: 2048
num_codebooks: 4
mode: encode

# Embedding parameters
embedding_dim: 1024
pretrain_embeddings: False  # If True, must match the codec's embedding size
freeze_embeddings: False

# Encoder parameters
hidden_size: 512
num_layers: 1
dropout: 0.1

# Augmentation
drop_freq: !new:speechbrain.augment.time_domain.DropFreq
    drop_freq_low: 0  # Min frequency band dropout probability
    drop_freq_high: 1  # Max frequency band dropout probability
    drop_freq_count_low: 1  # Min number of frequency bands to drop
    drop_freq_count_high: 3  # Max number of frequency bands to drop
    drop_freq_width: 0.05  # Width of frequency bands to drop

drop_chunk: !new:speechbrain.augment.time_domain.DropChunk
    drop_length_low: 1  # Min number of audio chunks to drop
    drop_length_high: 5  # Max number of audio chunks to drop
    drop_count_low: 1000  # Min length of audio chunks to drop
    drop_count_high: 2000  # Max length of audio chunks to drop

augmentation: !new:speechbrain.augment.augmenter.Augmenter
    parallel_augment: False
    concat_original: False
    repeat_augment: 1
    shuffle_augmentations: False
    min_augmentations: 2
    max_augmentations: 2
    augment_prob: !ref <augment_prob>
    augmentations: [!ref <drop_freq>, !ref <drop_chunk>]

# Tokenizer
tokenizer_cls: !name:speechbrain.tokenizers.SentencePiece.SentencePiece
    model_dir: !ref <save_folder>
    vocab_size: !ref <num_tokens>
    annotation_train: !ref <train_csv>
    annotation_read: wrd
    model_type: !ref <token_type>
    character_coverage: !ref <character_coverage>

# Codec
codec: !new:audiocodecs.Mimi
    sample_rate: !ref <sample_rate>
    num_codebooks: !ref <num_codebooks>
    mode: !ref <mode>

# Modules
embedding: !new:models.multihead.MultiHeadEmbedding
    vocab_size: !ref <vocab_size>
    embedding_dim: !ref <embedding_dim>
    num_codebooks: !ref <num_codebooks>
    _freeze: !ref <freeze_embeddings>

pooling: !new:models.pooling.LinearPooling
    num_channels: !ref <num_codebooks>

encoder: !new:speechbrain.nnet.RNN.LSTM
    input_size: !ref <embedding_dim>
    hidden_size: !ref <hidden_size>
    num_layers: !ref <num_layers>
    dropout: !ref <dropout>
    bidirectional: True

head: !new:torch.nn.Linear
    in_features: !ref <hidden_size> * 2
    out_features: !ref <num_tokens> + 1  # +1 for blank

modules:
    embedding: !ref <embedding>
    pooling: !ref <pooling>
    encoder: !ref <encoder>
    head: !ref <head>

model: !new:torch.nn.ModuleList
    [[!ref <embedding>,
      !ref <pooling>,
      !ref <encoder>,
      !ref <head>]]

# Loss functions
ctc_loss: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_id>
    reduction: mean

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 1.e-8
    weight_decay: !ref <weight_decay>

# Schedulers
scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
   split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <scheduler>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt