channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnsl=2.0.1
  - libsqlite=3.47.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alias-free-torch==0.0.6
      - annotated-types==0.7.0
      - anyio==4.8.0
      - appdirs==1.4.4
      - argbind==0.3.9
      - argparse==1.4.0
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==24.3.0
      - audioread==3.0.1
      - auraloss==0.4.0
      - av==11.0.0
      - babel==2.16.0
      - beartype==0.19.0
      - bibtexparser==2.0.0b8
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - cffi==1.16.0
      - charset-normalizer==3.4.0
      - clean-fid==0.1.35
      - click==8.1.8
      - clip-anytorch==2.6.0
      - clldutils==3.24.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - configparser==7.1.0
      - contourpy==1.3.0
      - csvw==3.5.1
      - ctranslate2==4.3.1
      - cycler==0.12.1
      - dctorch==0.1.2
      - decorator==5.1.1
      - descript-audio-codec==1.0.0
      - descript-audiotools==0.7.2
      - diffusers==0.31.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - einops-exts==0.0.4
      - einx==0.3.0
      - ema-pytorch==0.2.3
      - encodec==0.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.6
      - faster-whisper==1.1.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fire==0.6.0
      - flash_attn==2.7.4.post1
      - flatbuffers==24.3.25
      - flatten-dict==0.4.2
      - fonttools==4.55.0
      - frozendict==2.4.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - gammatone==1.0.3
      - gin-config==0.5.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.12.0
      - gradio-client==1.5.4
      - grpcio==1.67.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.2
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==5.12.0
      - ipython==8.29.0
      - isodate==0.7.2
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonmerge==1.9.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - julius==0.2.7
      - k-diffusion==0.1.1
      - kiwisolver==1.4.7
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - laion-clap==1.1.4
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning-utilities==0.11.9
      - lion-pytorch==0.2.2
      - llvmlite==0.43.0
      - local-attention==1.8.6
      - lxml==5.2.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdown2==2.5.1
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numba==0.60.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.17.3
      - orjson==3.10.14
      - packaging==24.2
      - pandas==2.0.2
      - parso==0.8.4
      - pathtools==0.1.2
      - pesq==0.0.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prefigure==0.0.9
      - progressbar==2.5
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==3.19.6
      - psutil==5.9.8
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pylatexenc==2.10
      - pyloudnorm==0.1.1
      - pyparsing==3.2.0
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-lightning==2.1.0
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - randomname==0.2.1
      - rdflib==7.1.1
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rfc3986==1.5.0
      - rich==13.9.4
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - ruff==0.9.1
      - safehttpx==0.1.6
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - segments==2.2.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soxr==0.3.5
      - stable-audio-tools==0.0.17
      - stable-codec==0.1.2
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - text2phonemesequence==0.1.4
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - timm==1.0.11
      - tokenizers==0.20.0
      - tomlkit==0.13.2
      - torch==2.4.0
      - torch-stoi==0.2.3
      - torchaudio==2.4.0
      - torchdiffeq==0.2.5
      - torchlibrosa==0.1.0
      - torchmetrics==0.11.4
      - torchsde==0.2.6
      - torchvision==0.19.0
      - tqdm==4.67.0
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.46.3
      - triton==3.0.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - v-diffusion-pytorch==0.0.2
      - vector-quantize-pytorch==1.14.41
      - vocos==0.1.0
      - wandb==0.15.4
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - websockets==14.1
      - werkzeug==3.1.3
      - wget==3.2
      - x-transformers==1.26.6
      - yarl==1.18.3
      - zipp==3.21.0
      # Install from git
      - bigcodec @ git+https://github.com/lucadellalib/BigCodec.git@main#egg=bigcodec
      - semanticodec @ git+https://github.com/haoheliu/SemantiCodec-inference@8dc464c3385d2389a695ed3f718f4a0caf3ed33f#egg=semanticodec
      - speechbrain @ git+https://github.com/lucadellalib/speechbrain@50ffdc772c0d977390025ee7787735db9b92488c#egg=speechbrain
      - stable_codec @ git+https://github.com/lucadellalib/stable-codec.git@main#egg=stable_codec
      - wavtokenizer @ git+https://github.com/lucadellalib/WavTokenizer.git@main#egg=wavtokenizer
      # Install local audiocodecs package in editable mode
      - -e ../
      - -e ../[all]
